/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/opHV3FOExMc
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Image from "next/image";

export function AdressLookup() {
  return (
    <section className="flex justify-center w-full py-12 md:py-24 lg:py-32">
      <div className="container space-y-8 px-4 md:px-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="space-y-4 text-center md:text-left">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Estimate Your Building Refitting
            </h1>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Enter your building number and post code to get a personalized
              carbon estimation for your building refitting.
            </p>
            <div className="flex max-w-xl flex-col space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="building">Building Number</Label>
                  <Input
                    id="building"
                    placeholder="Enter your building number"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="postcode">Post Code</Label>
                  <Input id="postcode" placeholder="Enter your post code" />
                </div>
              </div>
              <Button className="w-full" type="submit" to="/data">
                Get Estimate
              </Button>
            </div>
          </div>
          <div className="aspect-video overflow-hidden rounded-xl">
            <Image
              alt="Hero Image"
              className="h-full w-full object-cover"
              height="600"
              src="/adress.png"
              style={{
                aspectRatio: "800/600",
                objectFit: "cover",
              }}
              width="800"
            />
          </div>
        </div>
      </div>
    </section>
  );
}
